### ISSUE TITLE
Pluggable Authenticator

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/carbon-uuf#242]
It is required to have the ability to plug in any Authenticator implementation

**Comment by vidurananayakkara** [comment]
The authenticator implementation to be used should be able to be configured in the relevant app.yaml configuration along with the logout URL as shown below:

```yaml

...

# Authenticator for this app
authenticator: "org.wso2.carbon.uuf.sample.simpleauth.bundle.api.auth.FormParamAuthenticator"
logoutPageUri: "/simple-auth/logout"

...
```
